export const routes = {
  root: "/",
  save: "/save",
  run: "/runjob", 
  crontab: "/crontab",
  stop: "/stop",
  start: "/start",
  remove: "/remove",
  backup: "/backup",
  restore: "/restore",
  delete_backup: "/delete",
  restore_backup: "/restore_backup",
  export: "/export",
  import: "/import",
  import_crontab: "/import_crontab",
  logger: "/logger",
  stdout: "/stdout",
  health: "/health",
  metrics: "/metrics",
  status: "/status"
};
